### ISSUE TITLE
Tile (wrongly) showing markdown as language

### ISSUE THREAD

**Issue by cuteredpwnda** [LiquidFun/adventofcode#2]
In 2021 I tried using dart to solve the puzzles for the first three days (gave up afterwards). I included a README.md for each day to write down my ideas.

The tiles created now show `.md ` as language used, ignoring (?) the `.dart` files in `bin`.

**Comment by LiquidFun** [comment]
Apparently there is a programming language called GCC Machine Description, or something like that, which ends in .md...

https://github.com/LiquidFun/adventofcode/blob/ecb3c894e3ad239528badaa2a8ecd9d6caec119e/AoCTiles/github_languages.yml#L2076-L2080

Well, I think I'll just comment that one out until there is someone who uses that :shrug: 

It didn't find the dart files because it didn't look that deep in the bin folder, it looked only 1 layer deep. I'll fix this by adding a function which can be implemented by any other user which returns a dict of year to day to path to solution mappings, so that any file structure can be easily mapped.

**Comment by cuteredpwnda** [comment]
Oh my, this is a wild find. 

Nice idea!

**Comment by LiquidFun** [comment]
Solutions are now searched recursively (any depth) so the second part should be fixed as well.
